### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/app-icon#2]
### Is your feature request related to a problem? Please describe.
The Capacitor 3 RC is out! 🎉 This library should support the new version

### Describe the solution you'd like
Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0

### Additional context
The migration is pretty easy, I've done it for a couple plugins. Happy to assist if you need assisting!

I see you already have a v3 branch. Do you have plans on merging that into main or are you waiting on the full release?

**Comment by johnborges** [comment]
@thomasvidas The v3 branch will get merged within the week.
